# Generated by Django 6.1.1 on 2026-09-05 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SanctionedEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('entity_type', models.CharField(choices=[('person', 'Person'), ('organization', 'Organization')], max_length=20)),
                ('source_id', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['entity_type'], name='screening_s_entity__c11ad2_idx')],
            },
        ),
        migrations.CreateModel(
            name='ScreeningCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_score', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('network_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='screening.agent')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_type', models.CharField(choices=[('identifier_exact', 'Identifier Exact'), ('name_exact', 'Name Exact'), ('name_fuzzy', 'Name Fuzzy'), ('address_fuzzy', 'Address Fuzzy'), ('network_2nd_degree', '2nd Degree Network')], max_length=20)),
                ('confidence', models.IntegerField()),
                ('explanation', models.TextField(blank=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolution', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screening.sanctionedentity')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='screening.screeningcase')),
            ],
        ),
        migrations.CreateModel(
            name='EntityIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_type', models.CharField(choices=[('passport', 'Passport'), ('tax_id', 'Tax ID'), ('business_reg', 'Business Registration')], max_length=20)),
                ('value_hash', models.CharField(db_index=True, max_length=64)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='screening.sanctionedentity')),
            ],
            options={
                'indexes': [models.Index(fields=['id_type', 'value_hash'], name='screening_e_id_type_7c6f19_idx')],
            },
        ),
        migrations.CreateModel(
            name='EntityAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(db_index=True, max_length=255)),
                ('language', models.CharField(blank=True, max_length=10)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='screening.sanctionedentity')),
            ],
            options={
                'indexes': [models.Index(fields=['text'], name='screening_e_text_2893c6_idx')],
            },
        ),
        migrations.CreateModel(
            name='EntityAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('full_text', models.TextField(blank=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='screening.sanctionedentity')),
            ],
            options={
                'indexes': [models.Index(fields=['country_code'], name='screening_e_country_933cfd_idx')],
            },
        ),
    ]
