# Generated by Django 6.1.1 on 2026-09-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityidentifier',
            name='id_type',
            field=models.CharField(choices=[('passport', 'Passport'), ('tax_id', 'Tax ID'), ('business_reg', 'Business Registration'), ('other', 'Other')], max_length=20),
        ),
    ]
