# Generated by Django 6.1.1 on 2026-09-06 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0003_agent_addresses_trigram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanctionedentity',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
