# Generated by Django 6.1.1 on 2026-09-08 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0004_alter_sanctionedentity_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanctionedentity',
            name='is_target',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='agent',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
